//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string MIDDLE_1 = "middle_1";
        
        public const string MIDDLE_RIGHT_1 = "middle_right_1";
        
        public const string LEFT_3 = "left_3";
        
        public const string MIDDLE_RIGHT_3 = "middle_right_3";
        
        public const string MIDDLE_3 = "middle_3";
        
        public const string MIDDLE_LEFT_5 = "middle_left_5";
        
        public const string RIGHT_1 = "right_1";
        
        public const string LEFT_1 = "left_1";
        
        public const string RIGHT_3 = "right_3";
        
        public const string MIDDLE_LEFT_3 = "middle_left_3";
        
        public const string MIDDLE_LEFT_1 = "middle_left_1";
        
        public const string LEFT_5 = "left_5";
        
        public const string MIDDLE_5 = "middle_5";
        
        public const string RIGHT_5 = "right_5";
        
        public const string MIDDLE_RIGHT_5 = "middle_right_5";
    }
}
